apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-api
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-go-api
  template:
    metadata:
      labels:
        app: my-go-api
    spec:
      imagePullSecrets:           # ADD THIS SECTION
        - name: regcred             # ADD THIS LINE
      containers:
        - name: my-go-api
          image: REGISTRY_PLACEHOLDER/my-go-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: "dev"
            - name: PORT
              value: "8080"