name: CI/CD -> DigitalOcean (dev)

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: my-go-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      image: ${{ steps.image-meta.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup doctl
        uses: digitalocean/action-doctl@v2
        with:
          version: '1.97.0'
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Login and set image metadata
        id: image-meta
        run: |
          doctl registry login --expiry-seconds 1200
          IMAGE_TAG="${{ secrets.DOCR_REGISTRY }}/${IMAGE_NAME}:${{ github.sha }}"
          echo "image=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "Building: ${IMAGE_TAG}"

      - name: Build and push Docker image
        run: |
          docker build -t ${{ steps.image-meta.outputs.image }} .
          docker push ${{ steps.image-meta.outputs.image }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup doctl
        uses: digitalocean/action-doctl@v2
        with:
          version: '1.97.0'
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Configure kubectl
        run: |
          doctl kubernetes cluster kubeconfig save ${{ secrets.DO_CLUSTER_NAME }}

      - name: Create namespace and registry secret
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl -n dev delete secret regcred --ignore-not-found=true
          kubectl -n dev create secret docker-registry regcred \
            --docker-server=registry.digitalocean.com \
            --docker-username=${{ secrets.DO_API_TOKEN }} \
            --docker-password=${{ secrets.DO_API_TOKEN }} \
            --docker-email=noreply@example.com

      - name: Apply manifests and update deployment
        run: |
          kubectl apply -f k8s/service.yaml
          sed "s|REGISTRY_PLACEHOLDER|${{ secrets.DOCR_REGISTRY }}|g" k8s/deployment.yaml | kubectl apply -f -
          
          IMAGE_FROM_BUILD="${{ needs.build-and-push.outputs.image }}"
          FINAL_IMAGE="${IMAGE_FROM_BUILD:-${{ secrets.DOCR_REGISTRY }}/${IMAGE_NAME}:${{ github.sha }}}"
          
          kubectl -n dev set image deployment/${IMAGE_NAME} ${IMAGE_NAME}="${FINAL_IMAGE}"
          kubectl -n dev rollout restart deployment/${IMAGE_NAME}

      - name: Wait for deployment and show status
        run: |
          kubectl -n dev rollout status deployment/${IMAGE_NAME} --timeout=300s || {
            kubectl -n dev get deployment ${IMAGE_NAME} -o wide
            kubectl -n dev get pods -l app=${IMAGE_NAME} -o wide
            kubectl -n dev describe pods -l app=${IMAGE_NAME}
            exit 1
          }
          echo "✅ Deployment completed successfully"
          kubectl -n dev get pods -l app=${IMAGE_NAME}
          kubectl -n dev get service ${IMAGE_NAME}