name: CI/CD -> DigitalOcean (dev)

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: my-go-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      image: ${{ steps.image-meta.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate required secrets
        run: |
          if [[ -z "${{ secrets.DO_API_TOKEN }}" ]]; then
            echo "❌ DO_API_TOKEN secret is not set"
            exit 1
          fi
          if [[ -z "${{ secrets.DOCR_REGISTRY }}" ]]; then
            echo "❌ DOCR_REGISTRY secret is not set"
            exit 1
          fi
          echo "✅ All required secrets are configured"

      - name: Setup doctl
        uses: digitalocean/action-doctl@v2
        with:
          version: '1.97.0'
          token: ${{ secrets.DO_API_TOKEN }}

      # - name: Verify DigitalOcean access
      #   run: |
      #     echo "Testing DO API access..."
      #     if doctl account get; then
      #       echo "✅ Account access successful"
      #     else
      #       echo "❌ Account access failed - check token permissions"
      #       exit 1
      #     fi
      #
      #     echo "Testing registry access..."
      #     if doctl registry get; then
      #       echo "✅ Registry access successful"
      #     else
      #       echo "❌ Registry access failed - may need to create registry first"
      #       echo "Will attempt to continue..."
      #     fi

      - name: Login to DigitalOcean Container Registry
        run: |
          doctl registry login --expiry-seconds 1200

      - name: Generate image metadata
        id: image-meta
        run: |
          # Ensure we have the registry value
          if [[ -z "${{ secrets.DOCR_REGISTRY }}" ]]; then
            echo "❌ DOCR_REGISTRY secret is empty"
            exit 1
          fi
          
          IMAGE_TAG="${{ secrets.DOCR_REGISTRY }}/${IMAGE_NAME}:${{ github.sha }}"
          echo "DEBUG: Setting image output to: ${IMAGE_TAG}"
          echo "image=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          
          # Verify it was written
          echo "DEBUG: GITHUB_OUTPUT contents:"
          cat $GITHUB_OUTPUT
          
          echo "Building image: ${IMAGE_TAG}"

      - name: Build Docker image
        run: |
          docker build -t ${{ steps.image-meta.outputs.image }} .

      - name: Push Docker image
        run: |
          docker push ${{ steps.image-meta.outputs.image }}
          echo "✅ Image pushed successfully"

      - name: Verify output before job ends
        run: |
          echo "DEBUG: Checking job outputs before ending build job"
          echo "Image output: ${{ steps.image-meta.outputs.image }}"
          if [[ -z "${{ steps.image-meta.outputs.image }}" ]]; then
            echo "❌ ERROR: Image output is empty!"
            exit 1
          else
            echo "✅ Image output is set correctly"
          fi

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Debug received outputs
        run: |
          echo "DEBUG: All outputs from build-and-push job:"
          echo "${{ toJson(needs.build-and-push.outputs) }}"
          echo "DEBUG: Specific image output:"
          echo "${{ needs.build-and-push.outputs.image }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup doctl
        uses: digitalocean/action-doctl@v2
        with:
          version: '1.97.0'
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Configure kubectl
        run: |
          doctl kubernetes cluster kubeconfig save ${{ secrets.DO_CLUSTER_NAME }}

      - name: Verify cluster connection
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Create namespace if needed
        run: |
          kubectl apply -f k8s/namespace.yaml

      - name: Apply Kubernetes manifests
        run: |
          # Apply service first (order matters for some setups)
          kubectl apply -f k8s/service.yaml
          
          # Process deployment template
          sed "s|REGISTRY_PLACEHOLDER|${{ secrets.DOCR_REGISTRY }}|g" k8s/deployment.yaml > /tmp/deployment.yaml
          kubectl apply -f /tmp/deployment.yaml

      - name: Update deployment with new image
        run: |
          # Try to use the output from build job first
          IMAGE_FROM_BUILD="${{ needs.build-and-push.outputs.image }}"
          
          if [[ -n "${IMAGE_FROM_BUILD}" ]]; then
            echo "✅ Using image from build job: ${IMAGE_FROM_BUILD}"
            FINAL_IMAGE="${IMAGE_FROM_BUILD}"
          else
            echo "⚠️  Build job output is empty, reconstructing image name"
            FINAL_IMAGE="${{ secrets.DOCR_REGISTRY }}/${IMAGE_NAME}:${{ github.sha }}"
            echo "✅ Using reconstructed image: ${FINAL_IMAGE}"
          fi
          
          echo "Updating deployment with image: ${FINAL_IMAGE}"
          kubectl -n dev set image deployment/${IMAGE_NAME} ${IMAGE_NAME}="${FINAL_IMAGE}"

      - name: Wait for deployment
        run: |
          kubectl -n dev rollout status deployment/${IMAGE_NAME} --timeout=180s
          kubectl -n dev get pods -l app=${IMAGE_NAME}

      - name: Deployment summary
        env:
          FULL_IMAGE_NAME: ${{ secrets.DOCR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        run: |
          echo "✅ Deployment completed successfully"
          echo "Image: ${FULL_IMAGE_NAME}"
          echo "Namespace: dev"
          kubectl -n dev get service ${IMAGE_NAME} -o wide